services:
  # Serviço Web para a API FastAPI
  - type: web
    name: ocr-api
    env: python
    region: oregon # ou a região de sua preferência
    plan: free # ou o plano pago de sua preferência
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: connectionString
      - key: GROQ_API_KEY
        sync: false # Cole o valor diretamente no dashboard do Render
      - key: FRONTEND_URL
        sync: false # Cole a URL do seu deploy no Vercel

  # Worker para processamento em segundo plano com RQ
  - type: worker
    name: ocr-worker
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: connectionString
      - key: GROQ_API_KEY
        sync: false

  # Instância do Redis
  - type: redis
    name: ocr-redis
    region: oregon
    plan: free
    ipAllowList: [] # Permite acesso de qualquer lugar (ok para o plano free)
